# [[redirects]]
# from = "/"
# to = "/en"

#[[headers]]
#for = "/*"
#[headers.values]
#Content-Security-Policy = "default-src 'self';"

# Thanks to https://answers.netlify.com/t/no-changes-detected-in-base-directory-returning-early-from-build/11970
[[build.ignore]]
